# Generated by Django 2.2 on 2019-12-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191208_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Myuser')),
            ],
        ),
    ]
